spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/boot_book?rewriteBatchedStatements=true

    #-----------------------------------------------------------------------------------------#
    #要开启监控SQL和防火墙等功能不要自己在配置类创建数据库连接池,使用配置文件配置数据库连接池,否则失效#
    #-----------------------------------------------------------------------------------------#
    druid:
      aop-patterns: com.yt.boot.*  #监控SpringBean
      filters: stat,wall     # 底层开启功能，stat（sql监控），wall（防火墙）

      stat-view-servlet: # 配置监控页功能
        enabled: true
        login-username: admin
        login-password: admin
        resetEnable: false

      web-stat-filter: # 监控web
        enabled: true
        urlPattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

      filter:
        stat: # 对上面filters里面的stat的详细配置
          slow-sql-millis: 1000
          logSlowSql: true
          enabled: true
        wall:
          enabled: true
          config:
            drop-table-allow: false


      use-global-data-source-stat: true


server:
  servlet:
    context-path: /boot


mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true





